### ISSUE TITLE
Release 1.0.0 Roadmap

### ISSUE THREAD

**Issue by pedrovgs** [delr3ves/KuronometerServer#4]
I'd try to implement four features for this first release:

* Total build time since 25 of May 2017. The day the plugin was released.
    * We just have to update the landing with the first release date and improve the UI to show the formatted duration instead of the seconds.
* Top 10 projects with the fastest build.
* Top 10 projects with the slowest build. 
* Number of total builds counted by Kuronometer.
* Map with where the builds are being executed.

What do you think @delr3ves @davideme? I'd like to hear your proposals for this project.

**Comment by davideme** [comment]
Would be cool also, to keep the IP and setup a map with the builds.

**Comment by pedrovgs** [comment]
@davideme  I've updated the issue with your suggestion. What do you think each one sort the different ideas by preference so we can create 3 issues with the three most voted ideas?

**Comment by pedrovgs** [comment]
I'd go for:

1st -> Total build time since 25 of May 2017.
2nd -> Number of builds timed by kuronometer.
3rd -> Map with where the builds are being executed.

**Comment by delr3ves** [comment]
Cool @pedrovgs, I think for this very first version those metrics are good enough. 
We would also add some additional metrics like average, percentiles or deviation.

For future releases it'd also be cool providing a way to compare between languages, and build systems.

**Comment by pedrovgs** [comment]
Great! @davideme if you give me your ok I can create the issues!

**Comment by pedrovgs** [comment]
This is the list of features we are going to implement for our first version:

1st -> Total build time since 25 of May 2017.
2nd -> Number of builds timed by Kuronometer.
3rd -> Map with where the builds are being executed.
